{% set name = "DBnomics" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/DBnomics-{{ version }}.tar.gz
  sha256: 02e6039d10860f9d7dc99cd45ffe548934d4e1d373445d1a00b12fb057a0a6ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.18.4
    - pandas >=0.21
    # check https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#export-runtime-requirements

test:
  imports:
    - dbnomics
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.nomics.world/dbnomics/dbnomics-python-client
  summary: DBnomics Python Client
  license: AGPL-3.0-or-later
  license_file: LICENSE
  description: |
    Access DBnomics time series from Python.
  doc_url: https://git.nomics.world/dbnomics/dbnomics-python-client/-/blob/master/index.ipynb
  dev_url: https://git.nomics.world/dbnomics/dbnomics-python-client

extra:
  recipe-maintainers:
    - cbenz
    - michaelweinold
